sudo: required

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.25.0
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.4
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
- sed -e 's/${PYTHON_VERSION}/'${PYTHON_VERSION}/g Dockerfile.tmpl  > Dockerfile

before_script:
  - docker-compose up -d --build
  - docker-compose exec robot python tests/pre_data/pre_data.py

script:
  - docker-compose exec robot robot --pythonpath src tests

after_script:
  - docker-compose down


#
#deploy:
#  provider: pypi
#  user: ...
#  password: ...
#  skip_existing: true
#  on:
#    tags: true
